server:
  port: 8191

module:
  name: concurrent-user

cassandra:
  cluster-name: test-cluster
  keyspace-name: test
  contact-points: ip1,ip2,ip3
  port: 9042
  username: xiaoming
  password: password

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

default-filters:
  - name: Hystrix
    args:
      name: fallbackcmd
      fallbackUri: forward:/fallbackcontroller

spring:
  application:
    name: concurrent-user
  cloud:
    zookeeper:
      connect-string: "${ZOOKEEPER_URL:127.0.0.1:2181}"
    #      废弃consul注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
      ip-address: true
        #config:
        #discovery:
        #enabled: true
      #service-id: sc-config-server
      #fail-fast: true
      #username: root
      #password: booszy
      #profile: csdn
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
#  boot:
#    admin:
#      client:
#        username: ${username}
#        password: ${password}
#        enabled: true
#        url: http://localhost:8778
#        instance:
#          metadata:
#            user.name: ${username}
#            user.password: ${password}

username: "beanpodtech"
password: "doujia123456"

management:
  endpoints:
    web:
      exposure:
        include: "*"


