server:
  port: 8080
  #port: 8101
  
mybatis:
  type-aliases-package: me.monkey.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
time:
  cron: 0 0/1 * * * ?
  interval: 5


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50
    name-prefix: task-pool-prefix-

module:
  name: concurrent-system

spring:
  data:
    mongodb:
      database: ai_db
      host: 127.0.0.1
      #host: 47.93.32.73
      port: 27017

  application:
    name: concurrent-system
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshop?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
      ip-address: true
    config:
      discovery:
        enabled: true
        service-id: sc-config-server
      fail-fast: true
      #username: root
      #password: booszy
      #profile: csdn
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

snmp:
  config:
    v3User: root
    password: xxx
    isSnmp4JLogEnabled:  true